language: node_js
node_js:
    - "4.1"
scripts:
    test: "./node_modules/mocha/bin/mocha"
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: play.wc2js.com
    acl: public_read
    skip_cleanup: true
    detect_encoding: true
    local_dir: build
    on:
        branch: master
notifications:
    email:
        on_failure: always
        on_success: change
        recipients: 
        - jballaban@gmail.com
    